# Attributions for Poverty in Post-Socialist Countries - Markus Kainu & Mikko Niemelä

****

```{roptsattrib, echo=FALSE}
opts_chunk$set(echo=TRUE,eval=TRUE, cache=TRUE,message=FALSE,warning=FALSE,fig.width=12,fig.height=12)
```


# Introduction

This site gathers together all the data analysis behind the actual paper. Data analysis is broken down in three parts and each part is presented in .html format for human eyes and in text source including the R-code required for reproducing the analysis. As both the [micro data](http://www.ebrd.com/pages/research/publications/special/transitionII.shtml) and [macro data](http://www.qog.pol.gu.se/data/) are available as open data, anyone can rerun these analysis.

**Analytical code is licensed under open [FreeBSD](http://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29)-licence.**


# Data Analysis

## Cleaning the data & variable summaries

| html-ouput | source code |
| ------------ | -------------- |
| [loading, cleaning and summarizing](loadClean.html) | [source](loadClean.Rmd) |


## Descriptive analysis


| html-ouput | source code |
| ------------ | -------------- |
| [Descriptive analysis](descriptive_analysis.html) | [source](descriptive_analysis.Rmd) |
| [Spatial visualization](mapPlots.html) | [source](mapPlots.Rmd) |
| [Graphics in the paper](finalPlots.html) | [source](finalPlots.Rmd) |


## Modelling the data

| html-ouput | source code |
| ------------ | -------------- |
| [Regression analysis](regressionModelling.html) | [source](regressionModelling.Rmd) |



# Article draft


| pdf-ouput | source code |
| ------------ | -------------- |
| [Article draft in .pdf](article2013.pdf) | [source](article2013.Rmd) |


# Presentation slides

- [HSE Moscow - November 12, 2013](moscow2013/lcsr20131112.html)
- [Jatkokoulutusseminaari Turku November 7, 2013](turku2013/slidesTkuJatko20131107.html)
- [ESA Torino - August 29, 2013](torino2013/TorinoSlides2013_final.html)

# Misc links

- [Article code in github](https://github.com/muuankarski/attributions)
- [rustfare-package](http://markuskainu.fi/rustfare/) *- toolbox for R language for open welfare data from Russian Federation*
- [rOpenGov](http://ropengov.github.io/) *-  R Ecosystem for Open Government Data and Computational Social Science*
- [markuskainu.fi](http://markuskainu.fi) *- personal website*

-----

