# Regression modellining



```{r, eval=FALSE, echo=FALSE}
library(knitr)
library(markdown)
knit2html('regressionModelling.Rmd', 
          stylesheet="~/workspace/web/css/rmarkdown.css",
          options = c('toc', markdown::markdownHTMLOptions(TRUE)))

```


```{roptsattrib, echo=FALSE}
opts_chunk$set(echo=TRUE,eval=TRUE, cache=TRUE,message=FALSE,warning=FALSE,fig.width=12,fig.height=10)
```


```{rmultilevelLoadData}
#########################################
#########################################
setwd("~/workspace/lits/attributions/")

#########################################
load("~/workspace/lits/attributions/data/lits.RData")
df.model <- df[df$group_general != "Western Europe",]


```

`log of changes`

date      comment
--------  -------------------
20131103  Non multi-level logistic regression done but not interpret yet. Bivariate multilevel models the same. Multivariate multilevel models running over night.
20131105  Regression modelling almost finished. Bug in a software caused a delay. Will be fixed by Wed morning. Now the tables are there, but coef and model names are not customized.
20131106  Model names fixed. Multinomial models coming by midday


# Description

This page includes everything related to modelling of the data. [Click here for the final tables](finalTables.html). 

In this paper we have two depentend variables (DV) that are both binomial

1. support for social blame type of explanation
2. support for individual blame type of explanation


# Unilevel regression analysis

Unilevel is used here for making distinction between multilevel analysis later. *In the analysis of this chapter **no** contextual level variables are used*.

I'm using the University of California's resource [R Data Analysis Examples: Logit Regression](http://www.ats.ucla.edu/stat/r/dae/logit.htm) as a reference here.

## Bivariate logistic regression

### Explaining social blame

```{rUnilevelBivarSoc}
unbisoc.1 <- glm(pov.log.social ~ incsour3, data = df.model, family = "binomial")
unbisoc.2 <- glm(pov.log.social ~ edu2, data = df.model, family = "binomial")
unbisoc.3 <- glm(pov.log.social ~ income2, data = df.model, family = "binomial")
unbisoc.4 <- glm(pov.log.social ~ past.diff, data = df.model, family = "binomial")
unbisoc.5 <- glm(pov.log.social ~ future.diff, data = df.model, family = "binomial")
unbisoc.6 <- glm(pov.log.social ~ crise, data = df.model, family = "binomial")

```


```{rUnilevelBivarSocOutput, results='asis'}
library(texreg)

model.names = c("Transfer Dependency", "Education level",
                "Perceived income","Income compared to past",
                "Income compared to future","Effect of financial crises")

coef.names = c("(intercept)", 
               "Dependent vs. non-dependent",
               "Low education vs. non-low education",
               "Low income vs. high income",
               "Income has worsened vs. has not",
               "Income will worsen vs. will not",
               "Has affected great or fair amount vs. has not")

htmlreg(list(unbisoc.1,unbisoc.2,
             unbisoc.3,unbisoc.4,
             unbisoc.5,unbisoc.6),
        custom.model.names = model.names,
        custom.coef.names = coef.names,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
       caption="Simple logistic regression on social blame", caption.above=TRUE)


```

#### Interpretation

- all the predictors are statistically significant which means that the *null hypothesis* of 
    - The probability of supporting the social blame type of explanation decreases by `-0.16` if we compare individual who is dependent on tranfers with individual who is not dependent
    - The probability of supporting the social blame type of explanation decreases by `-0.08` if we compare individual with low education with individual with no-low education
    - The probability of supporting the social blame type of explanation decreases by `-0.59` if we compare individual with low perceived income with individual with high perceived income
    - The probability of supporting the social blame type of explanation decreases by `-0.39` if we compare individual whose income has worsened during the financial crisis with individual whose income has not worsened
    - The probability of supporting the social blame type of explanation decreases by `-0.49` if we compare individual who is expecting his income to worsen during the next four years with individual expects his income to remain at the same level or to increase
    - The probability of supporting the social blame type of explanation decreases by `-0.46` if we compare individual who has suffered *Great or fair amount* from the financial crisis with individual who has suffered *Little or not at all*
- As you would expect the model fit is the best in the case of *expected change in income*


### Explaining individual blame

```{rUnilevelBivarInd}
unbiind.1 <- glm(pov.log.individual ~ incsour3, data = df.model, family = "binomial")
unbiind.2 <- glm(pov.log.individual ~ edu2, data = df.model, family = "binomial")
unbiind.3 <- glm(pov.log.individual ~ income2, data = df.model, family = "binomial")
unbiind.4 <- glm(pov.log.individual ~ past.diff, data = df.model, family = "binomial")
unbiind.5 <- glm(pov.log.individual ~ future.diff, data = df.model, family = "binomial")
unbiind.6 <- glm(pov.log.individual ~ crise, data = df.model, family = "binomial")
```


```{rUnilevelBivarIndOutput, results='asis'}
library(texreg)
htmlreg(list(unbiind.1,unbiind.2,
             unbiind.3,unbiind.4,
             unbiind.5,unbiind.6),
        custom.model.names = model.names,
        custom.coef.names = coef.names,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
       caption="Simple logistic regression on individual blame", caption.above=TRUE)
```

#### Interpretation

- all the predictors, but *education level* are statistically significant
    - The probability of supporting the individual blame type of explanation increases by `0.49` if we compare individual who is dependent on tranfers to individual who is not dependent
    - The probability of supporting the individual blame type of explanation increases by `0.03` if we compare individual with low education with individual with no-low education. *This is not statistically significant*
    - The probability of supporting the individual blame type of explanation increases by `0.38` if we compare individual with low perceived income with individual with high perceived income
    - The probability of supporting the individual blame type of explanation increases by `0.32` if we compare individual whose income has worsened during the financial crisis with individual whose income has not worsened
    - The probability of supporting the individual blame type of explanation increases by `0.40` if we compare individual who is expecting his income to worsen during the next four years with individual expects his income to remain at the same level or to increase
    - The probability of supporting the individual blame type of explanation increases by `-0.53` if we compare individual who has suffered *Great or fair amount* from the financial crisis with individual who has suffered *Little or not at all*
- As you would expect the model fit is the best in the case of *expected change in income*


## Multivariate logistic regression

### Social blame

```{rUnilevelMulvarSoc}
mulbisoc.1 <- glm(pov.log.social ~  incsour3, data = df.model, family = "binomial")
mulbisoc.2 <- glm(pov.log.social ~  incsour3 +
                                    edu2, data = df.model, family = "binomial")
mulbisoc.3 <- glm(pov.log.social ~  incsour3 +
                                    edu2 +
                                    income2, data = df.model, family = "binomial")
mulbisoc.4 <- glm(pov.log.social ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff, data = df.model, family = "binomial")
mulbisoc.4 <- glm(pov.log.social ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff, data = df.model, family = "binomial")
mulbisoc.5 <- glm(pov.log.social ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff + 
                                    future.diff, data = df.model, family = "binomial")
mulbisoc.6 <- glm(pov.log.social ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff + 
                                    future.diff +
                                    crise, data = df.model, family = "binomial")

```


```{rUnilevelMulvarSocOutput, results='asis'}
library(texreg)
htmlreg(list(mulbisoc.1,mulbisoc.2,
             mulbisoc.3,mulbisoc.4,
             mulbisoc.5,mulbisoc.6),
        custom.coef.names = coef.names,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
       caption="Multiple logistic regression on social blame", caption.above=TRUE)

```



#### Interpretation

- all the predictors, but *education level* are statistically significant
    - The probability of supporting the individual blame type of explanation increases by `0.49` if we compare individual who is dependent on tranfers to individual who is not dependent
    - The probability of supporting the individual blame type of explanation increases by `0.03` if we compare individual with low education with individual with no-low education. *This is not statistically significant*
    - The probability of supporting the individual blame type of explanation increases by XXX` if we compare individual with low perceived income with individual with high perceived income
    - The probability of supporting the individual blame type of explanation increases by `0.32` if we compare individual whose income has worsened during the financial crisis with individual whose income has not worsened
    - The probability of supporting the individual blame type of explanation increases by `0.40` if we compare individual who is expecting his income to worsen during the next four years with individual expects his income to remain at the same level or to increase
    - The probability of supporting the individual blame type of explanation increases by `-XXX` if we compare individual who has suffered *Great or fair amount* from the financial crisis with individual who has suffered *Little or not at all*
- As you would expect the model fit is the best in the case of *expected change in income*



### Individual blame

```{rUnilevelMulvarInd}
mulbiind.1 <- glm(pov.log.individual ~  incsour3, data = df.model, family = "binomial")
mulbiind.2 <- glm(pov.log.individual ~  incsour3 +
                                    edu2, data = df.model, family = "binomial")
mulbiind.3 <- glm(pov.log.individual ~  incsour3 +
                                    edu2 +
                                    income2, data = df.model, family = "binomial")
mulbiind.4 <- glm(pov.log.individual ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff, data = df.model, family = "binomial")
mulbiind.4 <- glm(pov.log.individual ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff, data = df.model, family = "binomial")
mulbiind.5 <- glm(pov.log.individual ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff + 
                                    future.diff, data = df.model, family = "binomial")
mulbiind.6 <- glm(pov.log.individual ~  incsour3 +
                                    edu2 +
                                    income2 +
                                    past.diff + 
                                    future.diff +
                                    crise, data = df.model, family = "binomial")
```


```{rUnilevelMulvarIndOutput, results='asis'}
library(texreg)
htmlreg(list(mulbiind.1,mulbiind.2,
             mulbiind.3,mulbiind.4,
             mulbiind.5,mulbiind.6),
        custom.coef.names = coef.names,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
       caption="Multiple logistic regression on individual blame", caption.above=TRUE)
```

#### Interpretation

# Multinomial logistic regression

In multinomial setting we use variable `poverty`as DV. `Dont know` and `not stated` values are exluded from the analysis and we are left with following four values:

- Social Blame 
- Individual Blame
- Individual Fate
- Social Fate

Of the DV values we use `Social Blame` as a reference category as it is distinctive category and allows me to make clear interpretations of the significance of the predictors. ([source](http://stats.stackexchange.com/questions/34574/is-there-any-criterion-about-choosing-reference-factor-in-multinomial-logistic-r))


## Simple multinomial logistic regression

<!--

### using nnet-package

This model follows tutorial by UCLA [Multinomial regression](http://www.ats.ucla.edu/stat/r/dae/mlogit.htm) and it uses [nnet](http://cran.r-project.org/web/packages/nnet/index.html)-package.

-->

```{rmultiNomSimplennet, eval=FALSE, echo=FALSE}
library(nnet)
df.model$poverty2 <- relevel(df.model$poverty, ref = "Social Blame")
test <- multinom(poverty2 ~ incsour3 + edu2 + income2 +
                   past.diff + future.diff + crise, data = df.model)
#library(texreg)
#screenreg(list(test))
summary(test)$coefficients/summary(test)$standard.errors

# The ratio of the probability of choosing one outcome category over the
# probability of choosing the baseline category is often referred as relative
# risk (and it is also sometimes referred as odds as we have just used to
# described the regression parameters above). The relative risk is the right-hand
# side linear equation exponentiated, leading to the fact that the exponentiated
# regression coefficients are relative risk ratios for a unit change in the
# predictor variable. We can exponentiate the coefficients from our model to see
# these risk ratios.

exp(coef(test))

```



### using mlogit-package

This follows the example from [University of Toronto](http://www.utstat.toronto.edu/~brunner/oldclass/312f12/lectures/MultinomialLogitWithR.pdf) and [Discrete-Choice Logit Models with R by Philip A. Viton (October 26, 2013)](http://facweb.knowlton.ohio-state.edu/pviton/courses2/crp5700/5700-mlogit.pdf)



```{rmultiNomSimpleMlogit, results='markup'}
library(mlogit)
dat.mlogit <- df.model[,c("poverty","edu2","incsour3","income2",
                          "past.diff","future.diff","crise")]
 dat.mlogit <- mlogit.data(dat.mlogit, shape="wide", choice="poverty")
# ------- #
model.mlogit5 <- mlogit(poverty ~ 0 | incsour3 + edu2 + 
                                      past.diff + future.diff +
                                      crise, 
                               data = dat.mlogit, 
                               reflevel ="Social Blame")

summary(model.mlogit5)
```

### Interpretation


## Multilevel multinomial logistic regression

Can be modelled in R in Bayesian manner using either [ChoiceModelR](http://cran.r-project.org/web/packages/ChoiceModelR/index.html) and  [Zelig](http://cran.r-project.org/web/packages/Zelig/).


Marco Steenbergen discusses the stat theory and imlementation in Stata in this video

<iframe width="420" height="315" src="//www.youtube.com/embed/q_t9VerQ2ko" frameborder="0" allowfullscreen></iframe>


# Multilevel regression

## Bivariate analysis

### Social blame explained


```{rmultilevelBivarSoc}
library(lme4)
df.model$group_balinCis[df.model$cntry %in% c('Czech Republic',
                                        'Hungary','Bulgaria',
                                        'Poland','Slovakia',
                                        'Slovenia','Romania')] <- 'CEE'

df.model$group_balinCis[df.model$cntry %in% c('Armenia','Azerbaijan',
                                        'Belarus','Georgia',
                                        'Kazakhstan','Kyrgyzstan',
                                        'Moldova','Tajikistan',
                                        'Ukraine','Uzbekistan','Russia',
                                        'Estonia','Latvia','Lithuania')] <- 'CIS'
df.model$group_balinCis <- factor(df.model$group_balinCis, levels=c("CEE","CIS"))


bisoc.1 <- glmer(pov.log.social ~ incsour3+(1|cntry),
                        family = binomial(logit), data = df.model)
bisoc.2 <- glmer(pov.log.social ~ edu2+(1|cntry),
                        family = binomial(logit), data = df.model)
bisoc.3 <- glmer(pov.log.social ~ income2+(1|cntry),
                        family = binomial(logit), data = df.model)
bisoc.4 <- glmer(pov.log.social ~ past.diff+(1|cntry),
                        family = binomial(logit), data = df.model)
bisoc.5 <- glmer(pov.log.social ~ future.diff+(1|cntry),
                        family = binomial(logit), data = df.model)
 bisoc.6 <- glmer(pov.log.social ~ crise+(1|cntry),
                         family = binomial(logit), data = df.model)
 bisoc.8 <- glmer(pov.log.social ~ uw_gini+(1|cntry),
                         family = binomial(logit), data = df.model)
 bisoc.9 <- glmer(pov.log.social ~ gdpchange07.10+(1|cntry),
                         family = binomial(logit), data = df.model)
 bisoc.10 <- glmer(pov.log.social ~ wbgi_vae+(1|cntry),
                          family = binomial(logit), data = df.model)
bisoc.11 <- glmer(pov.log.social ~ group_analysis+(1|cntry),
                          family = binomial(logit), data = df.model)
bisoc.12 <- glmer(pov.log.social ~ group_balinCis+(1|cntry),
                          family = binomial(logit), data = df.model)
bisoc.13 <- glmer(pov.log.social ~ perGini+(1|cntry),
                          family = binomial(logit), data = df.model)

```


```{rmultilevelBivarSocOutputNOCI, results='asis'}

coef.names.multi = c("(intercept)", 
                      "Dependent","Low education",
                      "Low income","Income has worsened",
                      "Income will worsen","Has affected great or fair amount",
                      "Gini coefficient",
                      "Change in GDP between 2007 to 2010",
                      "Good governance","Cgroup","CgroupMod",
                     "Perceived Gini")

library(texreg)
htmlreg(list(bisoc.1,bisoc.2,
          bisoc.3,bisoc.4,
          bisoc.5,bisoc.6,
          bisoc.8,
          bisoc.9,bisoc.10,
             bisoc.11,bisoc.12,
             bisoc.13),
        custom.coef.names = coef.names.multi,
        naive = TRUE,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        include.pvalues=TRUE,
        caption="Bivariate social blame", caption.above=TRUE)


```

#### Interpretation




### Individual blame explained

```{rmultilevelBivarInd}
biind.1 <- glmer(pov.log.individual ~ incsour3+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.2 <- glmer(pov.log.individual ~ edu2+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.3 <- glmer(pov.log.individual ~ income2+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.4 <- glmer(pov.log.individual ~ past.diff+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.5 <- glmer(pov.log.individual ~ future.diff+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.6 <- glmer(pov.log.individual ~ crise+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.8 <- glmer(pov.log.individual ~ uw_gini+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.9 <- glmer(pov.log.individual ~ gdpchange07.10+(1|cntry),
                        family = binomial(logit), data = df.model)
biind.10 <- glmer(pov.log.individual ~ wbgi_vae+(1|cntry),
                         family = binomial(logit), data = df.model)
biind.11 <- glmer(pov.log.individual ~ group_analysis+(1|cntry),
                          family = binomial(logit), data = df.model)
bisoc.12 <- glmer(pov.log.individual ~ group_balinCis+(1|cntry),
                          family = binomial(logit), data = df.model)
bisoc.13 <- glmer(pov.log.individual ~ perGini+(1|cntry),
                          family = binomial(logit), data = df.model)


```


```{rmultilevelBivarIndOuputNOCI, results='asis'}

library(texreg)
htmlreg(list(biind.1,biind.2,
          biind.3,biind.4,
          biind.5,biind.6,
          biind.8,
          biind.9,biind.10,
          biind.11,biind.12,
             biind.13),
        custom.coef.names = coef.names.multi,
        naive = TRUE,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        use.packages=FALSE,
        include.pvalues=TRUE,
        caption="Bivariate individual blame", 
        caption.above=TRUE)


```

#### Interpretation

## Multivariate multilevel regressions


### Social blame type of explanation

```{rmultilevelMultiSoc}
library(lme4)

soc.0 <- glmer(pov.log.social ~ (1|cntry),
                      family = binomial(logit),
                       data = df.model)
soc.1 <- glmer(pov.log.social ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+(1|cntry),
                      family = binomial(logit),
                      data = df.model)
soc.2 <- glmer(pov.log.social ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+(1|cntry),
                       family = binomial(logit),
                       data = df.model)
soc.3 <- glmer(pov.log.social ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+(1|cntry),
                       family = binomial(logit),
                       data = df.model)
soc.4 <- glmer(pov.log.social ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+wbgi_vae+(1|cntry),
                       family = binomial(logit),
                       data = df.model)

```




```{rmultilevelMultiSocOutputNOCI, results='asis'}
coef.names.multi = c("(intercept)", 
                      "Dependent","Low education",
                      "Low income","Income has worsened",
                      "Income will worsen","Has affected great or fair amount",
                      "Gini coefficient",
                      "Change in GDP between 2007 to 2010",
                      "Good governance")

model.names.multi = c("Empty",
                      "Only individual",
                      "Gini added",
                      "GDP change added",
                      "Good governance added")

htmlreg(list(soc.0,
        soc.1,
        soc.2,
        soc.3,
        soc.4),
        custom.model.names = model.names.multi,
        custom.coef.names = coef.names.multi,
        naive = TRUE,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        include.pvalues=TRUE,
        caption="Logistic multilevel random intercept model for social blame type of explanation", 
        caption.above=TRUE)

```



#### Interpretation



### Individual blame type of explanation


```{rmultilevelMultiInd}


ind.0 <- glmer(pov.log.individual ~ (1|cntry),
                      family = binomial(logit),
                       data = df.model)
ind.1 <- glmer(pov.log.individual ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+(1|cntry),
                      family = binomial(logit),
                       data = df.model)
ind.2 <- glmer(pov.log.individual ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+(1|cntry),
                       family = binomial(logit),
                       data = df.model)
ind.3 <- glmer(pov.log.individual ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+(1|cntry),
                       family = binomial(logit),
                       data = df.model)
ind.4 <- glmer(pov.log.individual ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+wbgi_vae+(1|cntry),
                       family = binomial(logit),
                       data = df.model)

```


```{rmultilevelMultiIndOutputNOCI, results='asis'}
htmlreg(list(ind.0,
       ind.1,
       ind.2,
       ind.3,
       ind.4),
        custom.model.names = model.names.multi,
        custom.coef.names = coef.names.multi,
        naive = TRUE,
        ci.test = NULL,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        include.pvalues=TRUE,
        caption="Logistic multilevel random intercept model for individual blame type of explanation", 
        caption.above=TRUE)

```

### Comparison of full models with our last model 

```{rmultilevelMultivarFull}

soc.4 <- glmer(pov.log.social ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+wbgi_vae+(1|cntry),
                       family = binomial(logit),
                       data = df.model)

ind.4 <- glmer(pov.log.individual ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+wbgi_vae+(1|cntry),
                       family = binomial(logit),
                       data = df.model)

df.model$pov.log.socVsInc[df.model$poverty == "Social Blame"] <- 1
df.model$pov.log.socVsInc[df.model$poverty == "Individual Blame"] <- 0

socVsInc <- glmer(pov.log.socVsInc ~ incsour3+edu2+income2+
                        past.diff+future.diff+crise+
                        uw_gini+gdpchange07.10+wbgi_vae+(1|cntry),
                       family = binomial(logit),
                       data = df.model)

save(ind.0,ind.1,ind.2,ind.3,ind.4,
     soc.0,soc.1,soc.2,soc.3,soc.4,
     socVsInc, file="data/finalModels.RData")

```

# Tables for presentation

## Partial

```{rmultilevelMultivarSlideOutput, results='asis', eval=TRUE}
library(texreg)
coef.names.multi = c("(intercept)", 
                      "Dependent","Low education",
                      "Low income","Income has worsened",
                      "Income will worsen","Has affected great or fair amount",
                      "Gini coefficient",
                      "Change in GDP between 2007 to 2010",
                      "Good governance")

model.names.multi = c("Empty",
                      "Only individual",
                      "Gini added",
                      "GDP change added",
                      "Good governance added")

model.names.multi.A = c("SB empty",
                      "SB individual",
                      "SB all",
                      "IB empty",
                      "IB individual",
                        "IB all")

htmlreg(list(soc.0,soc.1,soc.4,
            ind.0,ind.1,ind.4),
        custom.model.names = model.names.multi.A,
        custom.coef.names = coef.names.multi,
        naive = TRUE,
        inline.css = TRUE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        include.pvalues=TRUE,
        caption="Logistic multilevel random intercept model for social and individual blame type of explanation", 
        caption.above=TRUE)
```

## Comparison of full models

```{rrmultilevelMultivarFullOutput, results='asis', eval=TRUE}
coef.names.multi = c("(intercept)", 
                      "Dependent","Low education",
                      "Low income","Income has worsened",
                      "Income will worsen","Has affected great or fair amount",
                      "Gini coefficient",
                      "Change in GDP between 2007 to 2010",
                      "Good governance")

model.names.multi.2 = c("Social blame vs. not",
                      "Individual blame vs. not",
                        "Social blame vs. Individual blame")

library(texreg)
htmlreg(list(soc.4,ind.4,socVsInc),
        naive = TRUE,
        custom.model.names = model.names.multi.2,
        custom.coef.names = coef.names.multi,
        inline.css = FALSE,
        doctype = FALSE,
        html.tag = FALSE,
        head.tag = FALSE,
        body.tag = FALSE,
        include.pvalues=TRUE,
        caption="Logistic multilevel random intercept model for social and individual blame type of explanation", 
        caption.above=TRUE)
```






